version: '3.7'
services:
  mysql:
    image: "mysql/mysql-server:5.7"
    environment:
      TZ: "Asia/Shanghai"
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: "actionview"
    networks:
      - net
    volumes:
      - mysql-data:/var/lib/mysql
    restart: "always"
  redis:
    image: "redis"
    command:
      - "redis-server"
      - "--databases 256"
    networks:
      - net
    volumes:
      - redis-data:/data
    restart: "always"
  frontend:
    image: "actionview-fe:latest"
    build:
      context: "."
      dockerfile: "front-end.Dockerfile"
    depends_on:
      - actionview
    ports:
      - "10011:8080"
    networks:
      - net
    restart: "always"
  actionview:
    image: "hyperf/biz-skeleton:latest"
    build:
      context: "."
    depends_on:
      - mysql
      - redis
      - elasticsearch
    environment:
      APP_ENV: "${APP_ENV:-prod}"
      DB_HOST: "mysql"
      REDIS_HOST: "redis"
      ELASTIC_SEARCH_HOST: "http://elasticsearch:9200"
      SCAN_CACHEABLE: "(true)"
    networks:
      - net
    restart: "always"
    deploy:
      replicas: 1
  elasticsearch:
    image: "elasticsearch:5-alpine"
    environment:
      discovery.type: "single-node"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    networks:
      - net
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    restart: "always"
networks:
  net:
volumes:
  mysql-data:
  redis-data:
  elasticsearch-data:
